import bcrypt from 'bcryptjs';
import { User } from '../models/index.js';

/**
 * Register a new user
 * @param {Object} userData - User registration data
 * @param {string} userData.email - User's email
 * @param {string} userData.firstName - User's first name
 * @param {string} userData.lastName - User's last name
 * @param {string} userData.password - User's password
 * @returns {Object} Registered user data
 */
export async function register(userData) {
  const { email, firstName, lastName, password } = userData;

  // Check if user already exists
  const existingUser = await User.findOne({ where: { email } });
  if (existingUser) {
    throw new Error('User with this email already exists');
  }

  // Hash password
  const saltRounds = 10;
  const passwordHash = await bcrypt.hash(password, saltRounds);

  // Create user
  const user = await User.create({
    email,
    firstName,
    lastName,
    passwordHash,
  });

  // Return user data without password hash
  const { passwordHash: _, ...userWithoutPassword } = user.toJSON();
  return {
    user: userWithoutPassword,
    token: null, // Token will be generated by the calling function
  };
}

/**
 * Login a user
 * @param {Object} credentials - User login credentials
 * @param {string} credentials.email - User's email
 * @param {string} credentials.password - User's password
 * @returns {Object} Login result with user data
 */
export async function login(credentials) {
  const { email, password } = credentials;

  // Find user by email
  const user = await User.findOne({ where: { email } });
  if (!user) {
    throw new Error('Invalid email or password');
  }

  // Check password
  const isPasswordValid = await bcrypt.compare(password, user.passwordHash);
  if (!isPasswordValid) {
    throw new Error('Invalid email or password');
  }

  // Return user data without password hash
  const { passwordHash: _, ...userWithoutPassword } = user.toJSON();
  return {
    user: userWithoutPassword,
    token: null, // Token will be generated by the calling function
  };
}
