name: Backend Tests

on:
  workflow_call:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GLASSCODE_CONTENT_PATH: ${{ github.workspace }}/content
      ASPNETCORE_URLS: http://127.0.0.1:8080
      SKIP_AUTOMATED_MIGRATION: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore backend tests
        run: dotnet restore glasscode/backend/Backend.Tests/Backend.Tests.csproj

      - name: Build backend tests
        run: dotnet build glasscode/backend/Backend.Tests/Backend.Tests.csproj --configuration Release --no-restore

      - name: Run tests
        run: |
          dotnet test glasscode/backend/Backend.Tests/Backend.Tests.csproj 
            --configuration Release 
            --no-build